### ISSUE TITLE
how to keep annotations specific to a page

### ISSUE THREAD

**Issue by Achenn** [dommmel/stampee#1]
hi- I have the following - (there may be some extraneous code, as I am a complete novice, and have managed to get things to work purely by luck).  When I create another page where the image source is different, the annotations I make on one page show up on the other.  Thanks

<body onload="init();">

<div style="position:relative; width:640px; height:400px; margin-bottom:20px;">

<div id="openseadragon1" style="width: 800px; height: 400px;"></div>

<a id="map-annotate-button" onclick="annotate(); return false;" href="#">ADD ANNOTATION</a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="http://openseadragon.github.io/openseadragon/openseadragon.js"></script>

<link rel="stylesheet" href="http://annotorious.github.com/latest/annotorious.css" type="text/css" />

<script src="http://annotorious.github.com/latest/annotorious.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

<script src="http://www.parsecdn.com/js/parse-1.2.8.min.js"></script>

<link rel="stylesheet" href="../wp-includes/css/anno-parse-plugin.css" type="text/css" />

<script src="../wp-includes/js/anno-parse-plugin1.js"></script>

<script>

anno.addPlugin('Parse', {

app_id: 'rYfdac06gfYhC2CHZwbcl5Jz6M5Y6rq1FSB2MZG3',

js_key: 'aIAyMXjct2pD5MG1jkOFDvgCEQfjZRVPdI4lJ4tf',

debug: true

});

</script>
    

<script>// <![CDATA[
Parse.initialize("rYfdac06gfYhC2CHZwbcl5Jz6M5Y6rq1FSB2MZG3", "aIAyMXjct2pD5MG1jkOFDvgCEQfjZRVPdI4lJ4tf");
var TestObject = Parse.Object.extend("TestObject");
var testObject = new TestObject();
testObject.save({foo: "bar"}).then(function(object) {
  alert("yay! it worked");
});

anno.addPlugin('Parse', { app_id: 'rYfdac06gfYhC2CHZwbcl5Jz6M5Y6rq1FSB2MZG3', js_key: 'aIAyMXjct2pD5MG1jkOFDvgCEQfjZRVPdI4lJ4tf', debug: true });
// ]]></script>

<script>
var dziFilesUrl = 'https://s3.amazonaws.com/maggpi.org/transfers/TCGA-CS-4942-01Z-00-DX1_files/';

var dziData = '<?xml version="1.0" encoding="UTF-8"?> <Image xmlns="http://schemas.microsoft.com/deepzoom/2008" Format="jpeg" Overlap="1" TileSize="256"> <Size Height="25915" Width="48921"/></Image>';

var tileSourceFromData = function(data, filesUrl) {
  var $xml = $($.parseXML(data));
  var $image = $xml.find('Image');
  var $size = $xml.find('Size');

  var dzi = {
    Image: {
      xmlns: $image.attr('xmlns'),
      Url: filesUrl,
      Format: $image.attr('Format'),
      Overlap: $image.attr('Overlap'),
      TileSize: $image.attr('TileSize'),
      Size: {
        Height: $size.attr('Height'),
        Width: $size.attr('Width')
      }
    }
  };  
  
  console.log(dzi);
  return dzi;
};
function annotate() {
        var button = document.getElementById('map-annotate-button');
        button.style.color = '#777';

        anno.activateSelector(function() {
          // Reset button style
          button.style.color = '#fff';
        });
      }

function init() { 

var viewer = OpenSeadragon({
  id: 'openseadragon1',
  prefixUrl: 'http://openseadragon.github.io/openseadragon/images/',
  tileSources: tileSourceFromData(dziData, dziFilesUrl),
showNavigator:  true,

});
anno.makeAnnotatable(viewer);}

anno.addPlugin('Parse', { app_id: 'rYfdac06gfYhC2CHZwbcl5Jz6M5Y6rq1FSB2MZG3', js_key: 'aIAyMXjct2pD5MG1jkOFDvgCEQfjZRVPdI4lJ4tf', });
</script>

</body>

<a href="http://maggpi.org/wp-content/uploads/2015/07/TCGA-CS-4942.052c9ff3-16ad-4219-8839-488297bead1f.pdf">Read the Pathology Report </a>

<h6>The images and data shown here are derived from data generated by the TCGA Research Network: <a href="http://cancergenome.nih.gov/" rel="nofollow">http://cancergenome.nih.gov/</a>.</h6>

**Comment by dommmel** [comment]
This is really an issue/question about https://github.com/dommmel/annotorious-parse-plugin

Try this branch which is context aware: https://github.com/dommmel/annotorious-parse-plugin/tree/context-aware
